/**
 * The festive wave-name roster and its pure lookup (#193). When "Festive Wave
 * Names" is on, a wave is labelled after a Discworld character instead of a bare
 * index. This module is pure — no I/O — so the naming is unit-testable and the
 * render/resume paths need no new machinery: a wave's name is a function of a
 * per-campaign `offset` plus the wave's index within the campaign.
 *
 * The offset is not stored (design §2.1: no cosmetic naming state on the durable
 * log). It is derived at render from the campaign's `campaign-start` timestamp
 * (`festiveOffsetFor`, dashboard-model.ts), so it is stable across every SSE
 * re-render and disjoint between campaigns started at different times.
 *
 * The pool is **fixed order** (never re-shuffled per render): a wave's name is
 * derived, not stored, so it must stay stable. Extend by appending, never reordering.
 */

/**
 * The fixed-order character roster festive wave names draw from (#193). Order is
 * canonical, not alphabetical — do not re-sort it; the cooling-off guarantee is that
 * consecutive offsets never collide until the roster wraps, which only holds while the
 * order is stable and the names unique. Extend by appending, never by reordering.
 */
export const DISCWORLD_NAMES: readonly string[] = [
  "Samuel Vimes",
  "Carrot Ironfoundersson",
  "Angua von Überwald",
  "Fred Colon",
  "Nobby Nobbs",
  "Detritus",
  "Cheery Littlebottom",
  "Reg Shoe",
  "Sally von Humpeding",
  "Dorfl",
  "Sybil Ramkin",
  "Granny Weatherwax",
  "Nanny Ogg",
  "Magrat Garlick",
  "Agnes Nitt",
  "Tiffany Aching",
  "Miss Tick",
  "Eskarina Smith",
  "Petulia Gristle",
  "Annagramma Hawkin",
  "Rob Anybody",
  "Daft Wullie",
  "Rincewind",
  "Mustrum Ridcully",
  "Ponder Stibbons",
  "The Librarian",
  "Windle Poons",
  "Coin",
  "Death",
  "Mort",
  "Susan Sto Helit",
  "Ysabell",
  "Albert",
  "Havelock Vetinari",
  "Moist von Lipwig",
  "Adora Belle Dearheart",
  "Cut-Me-Own-Throat Dibbler",
  "Leonard of Quirm",
  "Rufus Drumknott",
  "Harry King",
  "Reacher Gilt",
  "Mr Slant",
  "Groat",
  "Stanley",
  "Nutt",
  "Glenda Sugarbean",
  "Juliet Stollop",
  "Trevor Likely",
  "Twoflower",
  "Cohen the Barbarian",
  "Conina",
  "Nijel the Destroyer",
  "Creosote",
  "Victor Tugelbend",
  "Ginger",
  "Gaspode",
  "Imp y Celyn",
  "Glod Glodsson",
  "Cliff",
  "Brutha",
  "Vorbis",
  "Didactylos",
  "Teppic",
  "Ptraci",
  "Dios",
  "William de Worde",
  "Sacharissa Cripslock",
  "Otto Chriek",
  "Polly Perks",
  "Sergeant Jackrum",
  "Maladicta",
  "Lieutenant Blouse",
  "Lu-Tze",
  "Lobsang Ludd",
  "Jeremy Clockson",
  "Unity",
  "Verence II",
  "Hwel",
  "Tomjon",
  "Casanunda",
  "Jonathan Teatime",
  "Foul Ole Ron",
  "Mrs Palm",
  "Queen Molly",
  "Wee Mad Arthur",
  "Lord Rust",
  "Cosmo Lavish",
  "Big Yan",
  "Awf'ly Wee Billy Bigchin",
  "Wee Dangerous Spike",
  "Truckle the Uncivil",
  "Caleb the Ripper",
  "Mad Hamish",
  "Boy Willie",
  "Old Vincent",
  "Evil Harry Dread",
  "Vena the Raven-Haired",
  "Ronald Saveloy",
  "Visit-the-Infidel-with-Explanatory-Pamphlets",
  "Constable Downspout",
  "Buggy Swires",
  "Precious Jolson",
  "Lance-Constable Cuddy",
  "A.E. Pessimal",
  "Willikins",
  "Constable Haddock",
  "The Bursar",
  "The Dean",
  "The Senior Wrangler",
  "The Lecturer in Recent Runes",
  "The Chair of Indefinite Studies",
  "Hex",
  "Ymper Trymon",
  "Igneous Cutwell",
  "Mrs Earwig",
  "Gammer Beavis",
  "Old Mother Dismass",
  "Black Aliss",
  "Mrs Gogol",
  "Greebo",
  "Miss Level",
  "Granny Aching",
  "Miss Flitworth",
  "Mrs Cake",
  "Ludmilla",
  "Mr Ixolite",
  "Schleppel",
  "One-Man-Bucket",
  "Doctor Cruces",
  "Edward d'Eath",
  "Inigo Skimmer",
  "Lupine Wonse",
  "The Dragon King of Arms",
  "Lord Downey",
  "Mr Boggis",
  "Coffin Henry",
  "Arnold Sideways",
  "The Duck Man",
  "Altogether Andrews",
  "Sergeant Simony",
  "Urn",
  "Chidder",
  "Ptaclusp",
  "Copolymer",
  "Mr Pin",
  "Mr Tulip",
  "Gunilla Goodmountain",
  "Anghammarad",
  "Pucci Lavish",
  "Cribbins",
  "Mavolio Bent",
  "Dick Simnel",
  "Shufti",
  "Tonker",
  "Lofty",
  "Wazzer",
  "Igorina",
  "Wen the Eternally Surprised",
  "Qu",
  "Andy Shank",
  "Pepe",
  "Madame Sharn",
  "Lord Hong",
  "Pretty Butterfly",
  "Lotus Blossom",
  "Errol",
  "You Bastard",
  "The Luggage",
  "Death of Rats",
];

/**
 * The festive name for wave `waveIndex` of a campaign whose reserved block starts at
 * `offset` — `pool[(offset + waveIndex) % pool.length]`. Pure and total: the modulo
 * wraps so any non-negative pair resolves to a name. `offset` and `waveIndex` are
 * interchangeable (only their sum matters); the reservation cursor keeps concurrent
 * campaigns on disjoint offset blocks so their names never collide.
 */
export function festiveWaveName(offset: number, waveIndex: number, pool: readonly string[] = DISCWORLD_NAMES): string {
  return pool[(offset + waveIndex) % pool.length];
}
